# based on https://github.com/houseabsolute/precious/blob/master/.github/workflows/ci.yml
name: Build all targets

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ github.token }}
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: seccardgame
            name: seccardgamecli-Linux-x86_64-gnu.tar.gz
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: seccardgame.exe
            name: seccardgamecli-Windows-x86_64.zip    
          - os_name: macOS-aarch64
            os: macOS-latest # this runs on a M1 processor and currently uses macOS 14
            target: aarch64-apple-darwin
            bin: seccardgame
            name: seccardgamecli-MacOs-aarch64.tar.gz
          #  skip_tests: true
        toolchain:
          - stable
          
    steps:
      - uses: actions/checkout@v7
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: true
      - name: Run tests
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "test"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
        if: ${{ !matrix.platform.skip_tests }}
